version: '3.4'

services:
  issue:
    image: ${DOCKER_REGISTRY-}issue
    build:
      context: .
      dockerfile: issue\Dockerfile


  notification:
    image: ${DOCKER_REGISTRY-}notification
    build:
      context: .
      dockerfile: notification\Dockerfile


  ocelotgetway:
    image: ${DOCKER_REGISTRY-}ocelotgetway
    build:
      context: .
      dockerfile: OcelotGetway\Dockerfile

